name: chatgptdemo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_spinkit: ^5.1.0


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  connectivity_plus: ^3.0.4


dev_dependencies:

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/image/ic_launcher.png
  color_dark: "#121212"
  image_dark: assets/image/ic_launcher.png
  android_12:
    image: assets/image/ic_launcher.png
    icon_background_color: "#ffffff"
    image_dark: assets/image/ic_launcher.png
    icon_background_color_dark: "#121212"
  android: true
  ios: true

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/image/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
